# This is a basic workflow to help you get started with Actions

name: Dev subdir build for dev branch
#description: 'This action will make the dev branch available at /dev off of root'
#author: 'David Aspden david.aspden@gmail.com'

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "development" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
        with:
          ref: master

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          mkdir dev
          cp -r $GITHUB_WORKSPACE /dev
          cd dev
          echo -n '<h1>Dev Runner<h1>' > debug.htm
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: master
          folder: dev # The folder the action should deploy.
